### ISSUE TITLE
Mention Fortran Package Manager as a build system for Fortran

### ISSUE THREAD

**Issue by Beliavsky** [gjbex/Best-practices-in-programming#1]
At https://gjbex.github.io/Best-practices-in-programming/deployment/ you write

"For C, C++ and Fortran the build system of choice would be [CMake](https://cmake.org/)."

I suggest mentioning the Fortran Package Manager (FPM) for Fortran-specific projects. FPM is now widely used in the open source modern Fortran community.

I think your course is very good -- thanks. I especially liked the analogies between C++ and Fortran.

**Comment by gjbex** [comment]
@Beliavsky Thanks for mentioning this, I wasn't aware of FPM.  It reminds me a lot of poetry for Python (and I'm guessing that was a source of inspiration, or they share a common ancestor ;)
I'll also have a look at the testing framework mentioned in its documentation.

**Comment by gjbex** [comment]
Done.
